### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by motin** [iann0036/wildfire#3]
You mentioned in #1 that the extension is "as-is". Does this imply a ISC/MIT/BSD/MPL-2 license?
The extension is so beautiful, hope it can be openly licensed so that others can pick up and improve upon it! :)

**Comment by iann0036** [comment]
Happy for you (or anyone) to use as MPL-2 for now. I'll have to look into more permissible licensing - there are some entities being assholes about it currently.
